[package]
name = "rust-limit-order-book"
version = "0.1.0"
edition = "2021"
authors = ["Fanghao Yang"]
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
order-book = { path = "../order-book" }